build_binary:
    builder: particle photon
    source: firmware/
    script: make
    artifacts:
        - photon.bin

#testing:
#    script: testing/sample-test-script.py
#    device_update:
#        devices:
#            - $DEVID_1
#        ota_method: particle
#        binary: auto